versioned_plugins.rb

@jsvd Here is the change required to get the script to generate the correct paths.
At some point, we'll need some logic for determining how to update files in /include/6.x when the files in /logstash/docs/include/change. I created a versioned directory because I didn't want old plugin docs to pick up changes if/when we add or remove things like common options. So 6.x gives us a snapshot of the files. 
Edit: By "snapshot", I mean that I manually copied the files over to the 6.x directory. :-) If we make changes in /logstash/docs/include/change that we DO want in the 6.x folder, then we'll have to copy the files manually for now.

Update paths in build script

---

versioned_plugins.rb

Currently the versioned docs build script will compile the new docs,
test them, and either:
- abort the build if the test fails
- submit a PR if the test passes
Now that we have some confidence in the process (the build has been
producing PRs for the past two months), this commit changes the behaviour to:
- submit a PR if the test fails
- commit directly if the test passes
This way someone can manual fix the broken documentation directly in the PR
instead of having to reproduce the failure locally.

submit pr on versioned docs when build fails

---

settings.yml

Added repositories to skiplist for generated plugin docs:
- logstash-codec-s3plain # Incompatible with Logstash 6.x
- logstash-filter-anonymize # Incompatible with Logstash 6.x
- logstash-filter-unique # Incompatible with Logstash 6.x
- logstash-filter-multiline # Incompatible with Logstash 6.x
If anybody has insights on why we removed these, I'd be happy to update the comments to preserve that info.

Update skiplist for generated plugin docs

---

versioned_plugins.rb

The initial release of the Kafka Integration Plugin included links in its
changelog to the stand-alone _RabbitMQ_ plugins instead of the _Kafka_
plugins. By adding this fixup, we can ensure that versioned docs link
to the correct upstream changelogs.
See: https://github.com/logstash-plugins/logstash-integration-kafka/pull/3

versioned docs: patch versioned docs for Kafka Integration v10.0.0

---

versioned_plugins.rb

- remove link to non-org repo that was present in initial WIP for testing purposes
- include integration plugins in repo discovery by default.

Integration plugin versioned docs

---

lib/logstash-docket/plugin.rb
plugindocs.rb

In order to avoid overwriting individual plugins for releases that
are capable of running integration plugins, only write doc
entries for integration plugins that are marked as default.

Only publish integration plugins that are marked as default

---

settings.yml

Input-log4j was deprecated in 5.x. Recent restructuring in Beats documentation caused broken links in log4j. It doesn't make sense to release a new gem to a deprecated plugin. Instead, this PR adds input-log4j to the skiplist so that we won't pick up deprecations that I have to reverse each time we generate the plugin docs.  
Related: #45 #50
Note to self @karenzone and reviewer(s):  This updates one of three skiplists, and I hope it will solve the log4j regression problems.  Other skiplists: 
* Skiplist file - VPR: https://github.com/elastic/docs-tools/blob/master/versioned_plugins.rb
* Skiplist file - LSR: https://github.com/elastic/logstash/blob/master/rakelib/plugins-metadata.json
ToDo: Dig into other skiplist to see how they relate and if we can do some cleanup to avoid confusion. …

Add input-log4j to skiplist

---

build_docs.sh

This address is associated with the GitHub user, so it will make the CLA
Checker happy without needing to override it on PRs.

Update the email address used for logstashmachine git commits

---

README.versioned_docs.md
logstash/templates/docs/versioned-plugins/alias-index.asciidoc.erb
versioned_plugins.rb

Meta-issue: https://github.com/elastic/logstash/issues/12793
This PR change the `versioned_plugins` doc tool to recreate the files as in PR https://github.com/elastic/logstash-docs/pull/1021/files.
Introduce new ERB template for alias indices, processes Logstash aliases definition yml file to produce the asciidoc files.
Fixes #53

Fix asciidoc generation for aliased plugins

---

build_docs.sh

follow-up after https://github.com/elastic/logstash/pull/12763 is merged
have successfully tested  `./gradlew generatePluginsVersion` with 2g of heap, 
but let's not get overly optimistic :wink:

reduce memory for plugin versions generation

---

ci/generate_versioned_docs.sh
versioned_plugins.rb

* removes "test" flag and test code
* "dry-run" now skips creating the pull request instead of skipping pushing the commit
* don't create a PR if the destination branch exists in elastic/logstash-docs
fixes #51

create pull requests instead of auto merging

---

versioned_plugins.rb

Many field references being added to docs as a part of the ECS effort
contain the literal string `[source]`, so we need to be more conservative
about which instances of `[source]` we replace with `[source,shell]`.
By matching a regular expression instead of a substring, we can match
only the instances of `[source]` that are stand-alone on a line.
Example 🤦🏼: https://www.elastic.co/guide/en/logstash-versioned-plugins/current/v6.2.0-plugins-inputs-tcp.html#v6.2.0-plugins-inputs-tcp-ecs_metadata

fix: replace [source] only when stand-alone on line

---

logstash/templates/docs/versioned-plugins/alias-index.asciidoc.erb

Remove extra `the`. There's one in the actual text and one in the link text, and we don't need both.

Update landing page text to remove extra word

---

lib/logstash-docket/artifact_plugin.rb
lib/logstash-docket/repository.rb
lib/logstash-docket/source.rb
plugindocs.rb

related to https://github.com/elastic/logstash/issues/12052

change master branch references to main

---

logstash/templates/docs/versioned-plugins/plugin-index.asciidoc.erb
versioned_plugins.rb

**Issue:** https://github.com/elastic/docs-tools/issues/46
When customers visit versioned plugin reference pages and go through the links to stack versions, they will be always forwarded to `current` stack version documents. This leads confusion ([example reported issue](https://github.com/elastic/elastic-docs-prototype/issues/133)) and not guiding customers properly, [example case](https://github.com/elastic/logstash-docs/pull/1289).
This PR suggests to add stack version to the VPR docs when new plugin releases happen so that we can easily use that version to forward the customers to proper stack version reference pages.
Closes #46 
- Tested locally by creating a [support-stack-versions-in-vpr-docs-test](https://github.com/mashhurs/docs-tools/tree/support-stack-versions-in-vpr-docs-test) …

Support stack versions in versioned plugin docs.

---

logstash/templates/docs/versioned-plugins/plugin-index.asciidoc.erb

The attribute settings are causing the docs build to generate bogus content and are causing docs-ci to fail (with bad cross-document links).  Examples in https://github.com/elastic/logstash-docs/pull/1343, https://github.com/elastic/logstash-docs/pull/1344, and https://github.com/elastic/logstash-docs/pull/1345. 
We need to set the branch attributes for individual plugin version files (rather than in the index file) because the value will be different for different versions. I believe that the right fix will need to go in the applicable source files with conditional processing. (I'll handle that.) 
In the meantime, this fix _should_ stop the failures in the VPR docgen.

Remove attribute settings from index template

---

versioned_plugins.rb

When we support stack versions in VPR docs, we used ([through our discussion](https://github.com/elastic/docs-tools/issues/46)) [central release repo [master branch]](https://github.com/elastic/docs/blob/master/shared/versions/stack/master.asciidoc) to link. However, we checked that the master points to future releases, so that VPR docs should catch current stack release versions.
This PR introduces to replace master branch with current branch. Note that, current branch doc links to the current branch version doc, so that our logic pulls current version doc and retrieve stack versions from there.
Closes #74 
- Manually running the VPR scrip on local and check if doc-tool can fetch current stack versions:
Command: `bundle exec ruby versioned_plugins.rb --repair --skip-existing --dry-run …

Link current stack version instead feature releases.

---

versioned_plugins.rb

When building VPR docs, some links are broken ([e.g CI](https://elasticsearch-ci.elastic.co/job/elastic+logstash-docs+pull-request+build-docs/505/console)). The reason doc-tools using full versions in reference URLs but in a reality it should be major and minor only.
- Run following command on local: `bundle exec ruby versioned_plugins.rb --repair --skip-existing --dry-run --output-path=../`
- Output: before Logstash version was `8.2.0` which was wrong and now `8.2` will nor break URLs.
```
Current GitHub rate limit: 53/60
Warning! Api rate limit is close to being reached, this script may fail to execute
fatal: destination path '../logstash-docs' already exists and is not an empty directory.
Already on 'versioned_plugin_docs'
Stack version: 8.2
ECS version: 8.2
writing to ../logstash-docs …
```

Use major and minor versions in VPR URLs.

---

versioned_plugins.rb

This plugin is still being built. Once it's fully merged and publish this commit should be reverted.

Exclude logstash-integration-aws from versioned plugin docs

---

plugindocs.rb

When generating Plugin Reference Docs, embedded integration plugin meta changes are not correctly picked up. #79 and #80 issues are relative.
#80 happens when logstash machine generates the doc first and re-tries to generate with `skip-existing` option. So unnecessary contents will appear for the second try.
Closes #79 
Closes #80 
Embedded plugin should follow the integration plugin and use its meta data in the docs.
Logic generates the `plugins_version_docs.json` which contains the list of repositories with plugin details (default plugin and version, etc...). We iterate thought the repositories and generate the doc one-by-one for each plugin as well as plugin's dependencies (embedded and aliased plugins). There is a discrepancy which same job is repeated on same plugin with different …

Integration plugin docs repeteadly genereted issue fix.

---

generate_plugin_placeholder.rb
git_helper.rb
versioned_plugins.rb

- Adds a logic to generate an empty placeholder for new plugin
- currently we have an use-case for integration plugin only;
- it uses common template which later on can be used to fill released notes and dates;
- This change also adds a git helper to DRY.
- git operations are used in both VPR docs generator and placeholder generator, so created a git helper to DRY;
- Generated sample: https://github.com/elastic/logstash-docs/pull/1536
- How to run locally?
- Pull this change and run `ruby generate_plugin_placeholder.rb --output-path=/Users/mashhur/Dev/elastic --plugin-type=integration --plugin-name=testing` command
- Closes #90

A logic to generate an empty plugin placeholder. 

---

versioned_plugins.rb

After `logstash-integration-logstash` release, we need to enable docs generation on the plugin. This PR removes the plugin from the skip list to generate the docs.

Enable generating docs on ls-integration plugin.

---

ci/generate_versioned_docs.sh

Delete the CI directory and the generate_versioned_docs.sh script, as they are no longer needed due to https://github.com/elastic/logstash-docs/blob/main/.github/workflows/vpr.yml and https://github.com/elastic/infra/pull/39983/files

Delete ci directory

---

plugindocs.rb
versioned_plugins.rb

We hadn't a case where plugin repo is located in outside of `logstash-plugins` org. We have now `elastic_integration` plugin which is under the `elastic` org. 
1) VPR:  adds `elastic_integration` plugin to the plugin list. We automatically discover plugins under `logstash-plugins` org and list up the skip plugins. Since `logstash-plugins` is controlled by Logstash team, we can easily make changes. However, this is not a case with `elastic` org. So, for now, I have hard coded the plugin and open to change for any other options (I am also thinking if there is a better way).
2) While investigating, I have found some issues need to be addressed before publishing the plugin docs:
- parsing source code uri from gemdata
We [fetch gem information from …

Support plugin docs release outside of logstash-plugins org.

---

versioned_plugins.rb

See https://github.com/elastic/docs-tools/issues/115 to understand the issue.
This PR persists the last docs generated time into file and uses it for the next runs. It eliminates the issue where plugins docs missed when there is outstanding PR in logstash-docs.
We simulate https://github.com/elastic/logstash-docs/blob/main/.github/workflows/vpr.yml in our local env.
- Clone logstash-docs repo, checkout `versioned_plugin_docs` branch
- Pull this change and execute `bundle exec ruby versioned_plugins.rb --repair --skip-existing --dry-run --output-path=../ `. Note that `output-path` should be `logstash-docs` path

Persist last workflow run time and reference in next runs.

---

versioned_plugins.rb

Corrects the bug pushed the file name in this PR: https://github.com/elastic/docs-tools/pull/116

Fix the docs last generated file name.
